/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.visual;

/**
 *
 * @author rodrigo
 */
public class CadastroDependentes extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroDependentes
     */
    public CadastroDependentes() {
        initComponents();
        setRootPaneCheckingEnabled(false);  
	javax.swing.plaf.InternalFrameUI ui = this.getUI();  
	((javax.swing.plaf.basic.BasicInternalFrameUI)ui).setNorthPane(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LbNone = new javax.swing.JLabel();
        LbDtNascimento = new javax.swing.JLabel();
        TxtMaskDtNascimento = new javax.swing.JFormattedTextField();
        TxtNomeDependente = new javax.swing.JTextField();
        BtCancelar = new javax.swing.JButton();
        BtMais = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();

        setVisible(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro Dependentes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 260, 40);

        LbNone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbNone.setText("Nome Dependente:");
        getContentPane().add(LbNone);
        LbNone.setBounds(30, 100, 170, 22);

        LbDtNascimento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbDtNascimento.setText("Data Nascimento:");
        getContentPane().add(LbDtNascimento);
        LbDtNascimento.setBounds(30, 190, 150, 22);
        getContentPane().add(TxtMaskDtNascimento);
        TxtMaskDtNascimento.setBounds(30, 220, 160, 27);
        getContentPane().add(TxtNomeDependente);
        TxtNomeDependente.setBounds(30, 130, 400, 27);

        BtCancelar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtCancelar.setText("Cancelar");
        getContentPane().add(BtCancelar);
        BtCancelar.setBounds(20, 330, 100, 34);

        BtMais.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtMais.setText("Mais");
        getContentPane().add(BtMais);
        BtMais.setBounds(180, 330, 100, 34);

        BtSalvar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtSalvar.setText("Salvar");
        getContentPane().add(BtSalvar);
        BtSalvar.setBounds(340, 330, 100, 34);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtMais;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JLabel LbDtNascimento;
    private javax.swing.JLabel LbNone;
    private javax.swing.JFormattedTextField TxtMaskDtNascimento;
    private javax.swing.JTextField TxtNomeDependente;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
