/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc.visual;

/**
 *
 * @author rodrigo
 */
public class CadastraFuncao extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastraFuncao
     */
    public CadastraFuncao() {
        initComponents();
        
        setRootPaneCheckingEnabled(false);  
	javax.swing.plaf.InternalFrameUI ui = this.getUI();  
	((javax.swing.plaf.basic.BasicInternalFrameUI)ui).setNorthPane(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbTiuloFuncao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNomeFuncao = new javax.swing.JTextField();
        TxtSalario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListFuncoes = new javax.swing.JList();
        TxtDescricaoFuncao = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 579));
        getContentPane().setLayout(null);

        LbTiuloFuncao.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LbTiuloFuncao.setText("Cadastro de Função");
        getContentPane().add(LbTiuloFuncao);
        LbTiuloFuncao.setBounds(260, 30, 250, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Nome Função:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 110, 130, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Salario Base:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 175, 107, 22);
        getContentPane().add(TxtNomeFuncao);
        TxtNomeFuncao.setBounds(160, 100, 320, 27);
        getContentPane().add(TxtSalario);
        TxtSalario.setBounds(160, 170, 280, 27);

        ListFuncoes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ListFuncoes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Porteiro", "Serviços Gerais", "Jardineiro", "Sindico", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListFuncoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(540, 140, 210, 290);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        TxtDescricaoFuncao.setViewportView(jTextArea1);

        getContentPane().add(TxtDescricaoFuncao);
        TxtDescricaoFuncao.setBounds(30, 280, 480, 150);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Descrição da Função");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 240, 190, 22);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Funções Cadastradas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(550, 110, 190, 22);

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setPreferredSize(new java.awt.Dimension(70, 35));
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 470, 120, 35);

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Editar");
        jButton2.setPreferredSize(new java.awt.Dimension(70, 35));
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 470, 120, 35);

        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setText("Salvar");
        jButton3.setPreferredSize(new java.awt.Dimension(70, 35));
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 470, 120, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbTiuloFuncao;
    private javax.swing.JList ListFuncoes;
    private javax.swing.JScrollPane TxtDescricaoFuncao;
    private javax.swing.JTextField TxtNomeFuncao;
    private javax.swing.JTextField TxtSalario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
